apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: w5008j759-go 
  janus-idp.io/tekton: w5008j759-go
  backstage.io/kubernetes-id: w5008j759-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w5008j759-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml